config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts, only: %i[new create index destroy]
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name username])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @posts = Post.all.order('created_at DESC')
    @user = current_user
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    @user = current_user
    if @post.save
      redirect_to posts_path
      flash.notice = 'New post created!'
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash.notice = "Post '#{@post.title}' deleted!"
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def member?(sign)
    output = ''
    if sign == true
      output << link_to('Logout', destroy_user_session_path, method: :delete)
    else
      output << link_to('Sign In', new_user_session_path) + ' '
      output << link_to('Sign Up', new_user_registration_path)
    end
    output.html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAuthentication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav  style="background-color: #e3e3e3;">
      <div style="display:flex;justify-content: space-between; width: 40%;"> 
        <div>
          <%= member?(user_signed_in?) %>
        </div>
        <div>
          <%= link_to 'Home', posts_path, method: :get %>
        </div>
      </div> 
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  Title: <br> <%= f.text_field :title, value: 'Your Title' %><br>
  Body: <br> <%= f.text_area :body, value: 'Your post here' %>
  <br><%= f.submit value: 'Submit' %>
<% end %>

app/views/posts/index.html.erb
<h1> All Posts </h1>

<% if user_signed_in? %>
  <%= button_to 'Create Post', new_post_path, method: :get  %>
<% end %>

<div class= "posts">
  <% @posts.each do |post| %>
    <div class="post">
      <h3><%= post.title %></h3>
      <% if user_signed_in? %>
      <h6 class="member"> by <%= post.user.name %></h6>
      <% end %>
      <p><%= post.body %></p>
    </div>

    <% if @user && @user.admin %>
      <%= button_to "delete", post, method: :delete %> 
    <% end %>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>Create a Post</h1>

<%= render 'form' %>